XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX

XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
  XX XXXX XXXX XXXXX XXXXXX XX XXXX XXXXXXXXX XXXXX XXXX XXXXXXX XXXX XXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXX X
      XXX XXXXXXXXXXX X XXXXX
      XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
          XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
              XXX XXXXXX X XXXXXXXXXXXXXXXXXX
              XX XXXX XXXX XXXXXX XXXXXX XXXXX XXXX XXX XXXX XX XXXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                  XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                  XXXXXX
              X
          X
      X
      XXXXXX XXXXXXXXXXXX
  X
  XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
      XX XXXXX XXXX XXXXXXX XX XXX XXXXXXX XXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX X
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          X
      X
  XXX
XXXXXXXXX

XXXXXXXX

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    XX XXXX XXX XXXXXXX XX XXXXXX XXX
    XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXX
    XXXXXXXXXXXXX XX X
      XXXXX XXXXXXXXXX X XXXXXXXXXX

      XX XXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXX XXX XXXXXXXXXXX X
        XX XXXXXXXXXXX XXX XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        X XXXX XX XXXXXXXXXXX XXX XXXXXXXXXXX
          XX XXXXXXX XXXXX XXXXXXX XX XXX XXXX
          XXX XXXXXX X XXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        X
      X
      XXXX X
        XX XXX XXXX XX XXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
        XX XXXXXX
      X
    XXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXX
    XXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXX

      XXX XXXXX X XXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXX XXXXXXXXXXX X XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXX
        XXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXX
      XXXXXXXXXXXXX XX X
        XX XXXXX XX XXX XXXXXX XXXX XXX XX XXXXX XXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXX
      XXX
    XXX
  XXX

XXXXXXXXX