XXXXXXXXX XXXXX
XXXXXX
  XXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
    XXXXX XX X XXXXXXXXXXXXXXXXX
        XXXX XBBB BBBBBBBBBBXX
        XXXXXXX XXXXXXXXXXXXXX
        XXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXX XX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
          XXXXXX XXXXXXXX
        X
      XX
    XXXXXXXXX
  XXXXXXX
XXXXXXX