# Generated by Django 3.0.5 on 2021-03-11 18:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='message_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/app/mediafiles'), upload_to='message_storage'),
        ),
    ]
